### ISSUE TITLE
Need an AAR package in Maven central

### ISSUE THREAD

**Issue by Wavesonics** [hayribakici/infiniteviewpager#2]
It would be great to get an AAR of this in the maven central repo so we can use this inside Android Studio projects.

**Comment by hayribakici** [comment]
hmm.. that sounds plausible. I haven't done this before, however I will give it a try. I will put it as an enhancement request :)

**Comment by Wavesonics** [comment]
Cool! This looks like a good resource for how to do it:
http://gmariotti.blogspot.it/2013/09/publish-aar-file-to-maven-central-with.html

**Comment by hayribakici** [comment]
Thank you i will check it out

**Comment by SwampMobile** [comment]
+1 for this enhancement.  First I tried to use the maven repository as an Android Studio dependency but there was some issue with resolving InfiniteViewPager's dependency on the support library.  Then I downloaded this project and tried to add it as a library in my Android Studio project.  Unfortunately that failed because I wasn't clear on what I had to do to wrap it with Gradle.  Finally I had to copy and paste the source files over to my primary project.  Now its working well.

**Comment by jcraw** [comment]
The version in maven looks for an older support library (13) than is being used in my project, so it will not compile.  Can you update this to look for a minimum support version instead of exact match?

**Comment by hayribakici** [comment]
Sure. I can do this.

The version in maven looks for an older support library (13) than is being
used in my project, so it will not compile. Can you update this to look for
a minimum support version instead of exact match?

**Comment by hayribakici** [comment]
For this issue, there is a jitpack version out. You can get it through gradle with
`implementation 'com.github.hayribakici:infiniteviewpager:0.4.4'`

I am closing this issue now.
