### ISSUE TITLE
Allow user to set current item

### ISSUE THREAD

**Issue by SwampMobile** [hayribakici/infiniteviewpager#7]
Let the user explicitly set the current item by providing an Indicator:

``` java
adapter.setCurrentIndicator(indicator)
```

There is already a package private method with this signature but it's not accessible publicly and it looks to require some added implementation.  I changed it to the following and everything is working for me:

``` java
/**
  * Sets {@code indicator} as the current visible indicator.
  * @param indicator a indicator value.
  */
public void setCurrentIndicator(final T indicator) {
  mCurrentIndicator = indicator;
  fillPage(PAGE_POSITION_CENTER);
  fillPage(PAGE_POSITION_LEFT);
  fillPage(PAGE_POSITION_RIGHT);
  notifyDataSetChanged();
}
```

**Comment by hayribakici** [comment]
Hi,
this feature is already in the viewPager
viewPager.setCurrentIndicator(Object indicator).
You should use this method instead, because it makes some more checks.
The original PagerAdapter from android does not provide such method and it is not the responsibility of an adapter to provide such functionality. But it is the responsibility of the ViewPager, what it is showing.
