### ISSUE TITLE
InfiniteViewPager setCurrentItem not display fragment content

### ISSUE THREAD

**Issue by Bhavdip** [hayribakici/infiniteviewpager#9]
After swipe the infiniteviewpager fragments number of times,For navigate on particulate fragment programatically we call the setCurrentItem , It show the fragment with blank, sometime come the fragment with out layout when we try to touch the fragment it show the content of current fragment.

**Comment by hayribakici** [comment]
Hi,
Are you using fragments as pages? If so, the infinite view pager is not
suitable for many fragments (I assume you have many). The issue in your
case might be, that the state of the fragment you are trying to go to after
calling setCurrentItem is because, the state of the fragment has not been
restored. Therefore you see nothing. This infinite view pager is suitable
for normal layouts as to fragments.
If you want to display many fragments in the viewapager I would suggest you
to use the FragmentStatePagerAdapter.

Cheers

**Comment by Bhavdip** [comment]
Hi thank you for quick reply 

I had predefined 5 fragments as pages that I would like to apply circular look, I have no issue with swipe from left to right, right to left, It was worked fine infinite time but I when i used setCurrentItem(int position,boolean smoothscrolling) in the click of action bar menu item for direct jump among one of 5 fragments It show the blank fragment,sometime it show the layout correct but in many case it will not show the layout

As you said it is might be fragment state not restore, about FragmentStatePagerAdapter I did not tried before,but I will try using FragmentStatePagerAdapter might be help.

Thank you

**Comment by Bhavdip** [comment]
As I seen to make viewpager infite we were created the virtual position I had the 5 fragments when I swipe the viewpager numbers of time, the position of fragmens might be virtual number, when i used the setCurrentItem with position with the number out of 5 It could not able to restore that fragment.
